### ISSUE TITLE
git alarm 설정 (git 채널)

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_5_dataanalysis#18]
git alarm 설정 (git 채널)
- PR 올 때, Review 대상자 지정, commit 설정

**Comment by oh-bom** [comment]
@syleeie2310 
안녕하세요 멘토님 저번에 말씀해주신 그룹 단위로 assign 하는 것 관련 질문드립니다!! 제가 이것저것 다른 레포지토리에서 실험을 해보았는데, 그룹을 만들어서 해당 그룹에 요청을 하는게 assignees 에서는 안되고, pr 올릴때 reviewers 지정시 그룹요청이 가능하더라구요! 혹시 assignees가 아니라 reviewers 지정때 그룹 지정을 원하셨던게 맞을까요??

**Comment by syleeie2310** [comment]
@oh-bom 네 그룹 단위로 assign 하는건 PR 쪽 revieweres 인데 제가 전달 과정에서 오해가 있었나 보군요. 그렇게 부탁드려요!

**Comment by syleeie2310** [comment]
그리고 issue 에서 코멘트 남기거나 PR에서 피드백 있을 경우 슬랙 git 채널에도 알람 연동되어야 될듯 합니다.

**Comment by oh-bom** [comment]
@

> 그리고 issue 에서 코멘트 남기거나 PR에서 피드백 있을 경우 슬랙 git 채널에도 알람 연동되어야 될듯 합니다.

넵 반영했습니다!
