### ISSUE TITLE
현재 구글맵에서 추천 방식이 어떻게 되는지 리서치

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_5_dataanalysis#20]
- google 검색하여 구글맵 추천시스템이 어떻게 구성되어 있는지 자료가 나와있을 수 있음 (논문, 블로그)
- 실제 추천되는 리스트 확인해보면서 (ex, 하와이) 어떻게 데이터 나오는지? 
- 구글 Word로 정리해보기

**Comment by syleeie2310** [comment]
호텔 : 근처에 비슷한 아이템 정의가 무엇일지? 그런 유형들이 몇개나 있는지?

**Comment by YoonjungJang** [comment]
구글맵 리서치 (추가) - 카테고리별 추천 항목
https://docs.google.com/presentation/d/1I9qQrlRuorroVQEcZCuM2MPzphRgMwEw59e09oenoww/edit?usp=sharing
