### ISSUE TITLE
하와이 메타 데이터 탐색

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_5_dataanalysis#22]
- avg_rating
- num_of_reviews
- relative_results
ㄴ갯수 분포가 다를 수도 있기 때문에 확인 필요

가격 좀 더 정확하게 알아야 되는 문제
카테고리 나눠서 본다고 하면 갯수 보고 ETC로 나눈다거나.

**Comment by syleeie2310** [comment]
- gmap_id랑 유니크가 다름 (86개 동일한 데이터가 2개식 있었음)
ㄴ 특정 컬럼이 다른 경우를 나중에 전체 데이터 확장할 때 봐야함
- 폐업인 경우 점수가 낮은지 비율 검정 필요 (통계적으로 차이가 있는지?)
- 리뷰 데이터 gmap_id 리뷰 건수 & 메타 데이터에서 나오는 num_of_reviews 값이 차이가 있을거 같은데. 어떨지?
- 리뷰 추천 갯수
ㄴ 최대 5개 : 11,503개 

- 리뷰 숫자와 & 평점
ㄴ x축, y축이 다를때 원 데이터로 봤을 떄 특성이 없어 보이는데 x축 (log, exp)

- 가격
ㄴ $, # 케이스 눈으로 확인

**Comment by Seolhada** [comment]
전체 지역의 메타데이터 EDA 정리한 링크입니다!
https://quirky-age-880.notion.site/EDA-2ecefd7df8b44fb2ada87b9eda853ada?pvs=4

하와이 지역 메타데이터 EDA는 추가로 한 내용까지 정리한 후 최종으로 링크 남겨두도록 하겠습니다!

**Comment by Seolhada** [comment]
하와이 지역 간략한 EDA와 추가적인 메타데이터 EDA 정리한 링크입니다!
https://quirky-age-880.notion.site/EDA-ce7f51ac7bf949db8b35d637c6c0a9bf

**Comment by syleeie2310** [comment]
@Seolhada 정리 고생하셨어요!
