### ISSUE TITLE
리뷰 텍스트 데이터 탐색 (하와이)

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_5_dataanalysis#23]
- 텍스트 리뷰 길이
- WordCloud 확인
- NGRAM
ㄴ 2글자, 3글자, 4글자 나눠서 데이터 분포 확인 필요
ㄴ 어떤 형태소를 선택해서 볼거냐? (패턴을 정의해서 하기도 함)

**Comment by syleeie2310** [comment]
- da_cluster에서 작업할 것 (https://sparknlp.org/)
ㄴ https://www.johnsnowlabs.com/scaling-up-text-analysis-best-practices-with-spark-nlp-n-gram-generation/

- 형태소 분리해서 worldcloud 로 처리

**Comment by syleeie2310** [comment]
아래 코드 참고할 것
https://github.com/da-analysis/asac_4_dataanalysis/blob/main/1.%EC%A0%84%EC%B2%98%EB%A6%AC%26EDA/0323_review_text.py
https://github.com/da-analysis/asac_4_dataanalysis/blob/main/1.%EC%A0%84%EC%B2%98%EB%A6%AC%26EDA/0406_text.py

**Comment by syleeie2310** [comment]
어떤 클러스터에서 할지 패키지 설치 등은 제가 확인해보고 말씀드릴게요.

**Comment by syleeie2310** [comment]
da-text-cluster에 spark.nlp 설치 올려놧으니깐, spark-nlp 공부해서 그거 쓰세요! @heesunTukorea

**Comment by syleeie2310** [comment]
오전에 세팅 해놨는데 말한다는걸 깜박했네요 ;;

**Comment by syleeie2310** [comment]
- 토큰갯수 평균 164개
- spark nlp 파이프라인 만들어서 돌리는데 컬럼에 대한 이해를 하면서 찾고 있었음
- 노트북를 데이터 전처리, 워드 클라우드, NGRAM 분리해서 작업하는 것을 권장하고 오래걸리는 영역은 git 이슈에 적어주세요~

**Comment by heesunTukorea** [comment]
리뷰텍스트 노션입니다 추후 업데이트 될 예정입니다

https://quick-celsius-ee6.notion.site/review_text-a954c6b769d34a1988a519962e8bb5be?pvs=4

**Comment by syleeie2310** [comment]
- food, place, service, time, staff, google, translate, price, beach
- ngram 2,3,4

재방문 의사가 4gram 가 왔음

- 1점만 따로 뽑아서 봐도 될듯

**Comment by syleeie2310** [comment]
SBERT 논문 리뷰

허깅 페이스에 있는 모델 확인해보기
- https://huggingface.co/sentence-transformers

허깅페이스 모델 작은 것
-https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

**Comment by syleeie2310** [comment]
해보고 안되면 수요일날 spark nlp > sbert로 데이터 저장부터 하기

**Comment by syleeie2310** [comment]
BERT 리서치
- 토큰 임베딩, 세그먼트 임베딩, 위치 임베딩
- 임베딩을 합산하여 입력으로 제공
SBERT 리서치
- 문장간 유사도를 구하는 것 100X100 느리다
- 임베딩 + 코사인 유사도

nobic embedding
-> nomic-embed / sentence embedding

**Comment by syleeie2310** [comment]
토요일까지 SBert / Nomic 임베딩 데이터 저장 필요.

**Comment by syleeie2310** [comment]
텍스트 리뷰를 sBERT로 저장하고 나서 어떤 방향으로 활용할지
ㄴ sentence embedding -> document embedding
