### ISSUE TITLE
아이템 추천 모델 (분류기 실험) 필요

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_5_dataanalysis#32]

**Comment by syleeie2310** [comment]
relative_results 존재하지 않는 gmap_id이 비율 : 53.4%
테스트 데이터 나누기
AUC 기반 (실험)

**Comment by syleeie2310** [comment]
- 8:2 (co-count)
- gmap_count1, gmap_count2
- year : 숫자
- quater : 기준
- 오늘 보여준 피쳐 리스트 notion 링크 올려주세요~ 

- sampling 작업만 따로 나눠서 진행 하기 (서버리스)
- category feature 처리 방법 -> array 로 변경해서 vector 로 사용할 수 있게 전처리 필요 (좀 찾아봐야 될거 같은데 좋은 방법이 생기면 공유해줄게요)

ㄴ 참고? : https://spark.apache.org/docs/latest/ml-features.html#featurehasher

**Comment by Seolhada** [comment]
적절한 라벨, 샘플링 찾는 실험 진행중입니다
https://quirky-age-880.notion.site/dd117795d77d4dde9e657474cb259dd6

**Comment by Seolhada** [comment]
![image](https://github.com/user-attachments/assets/07cd86b7-63e6-4792-85bb-fcbb5a46909c)
@syleeie2310 멘토님, 현재 라벨과 샘플링 실험하고 있는데 코드가 이 상태로 너무 오래걸리는데 코드가 문제 있는걸까요?

**Comment by Seolhada** [comment]
![image](https://github.com/user-attachments/assets/7b2652e9-d58f-4309-afb8-3bd7bc2f9738)
@syleeie2310 멘토님....AUC가 너무 높게 나와서 확인해보니 모델이 냅다 0으로 다 찍어서 높게 나오는 것은데....이래도 일단 라벨링과 샘플링 기준 모두 실험을 해보는게 맞을까요? 아님 feature를 추가해야할까요?

**Comment by syleeie2310** [comment]
import mlflow

mlflow.autolog(
    log_input_examples=False,
    log_model_signatures=True,
    log_models=True,
    disable=False,
    exclusive=False,
    disable_for_unsupported_versions=True,
    silent=False
)

**Comment by syleeie2310** [comment]
모델 다음에 실험할 때 아래 2가지 후보가 있으니 다음에 참고하세요!
spark.mllib.gbdt () 또는 xgboost (https://docs.databricks.com/en/machine-learning/train-model/xgboost.html) 로도 실험 가능 (spark용 xgboost)

xgboost 실험하기 위해서는 단 databricks runtime ML이어야 합니다.

**Comment by syleeie2310** [comment]
분류기 모델 노트북 (V3) 제가 찾아서 serverless compute 돌려보면서 제가 문제를 확인해봤습니다.

**[노트북]**
https://tacademykr-asacanalysis.cloud.databricks.com/?o=3001521127938963#notebook/2862523437523428/command/2862523437523429

- 하나하나 돌려보니깐 카테고리 처리 이전에도, 조인이랑 group by 등 한번에 처리해야 될 데이터 크기가 너무 크네요.
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/79f30300-87aa-4a65-9c45-4985643a8fbc">
- 카테고리 처리가 문제인줄 알았는데 다시 보니 그게 아니라 한번에 모든걸 하려다보니 1대 컴퓨터에선 메모리 부족 상황이 발생했을거 같아요.
- 사용하는 클러스터는 ML 실험에는 적절하나, 중간에 데이터 처리할 때는 메모리를 크게 읽어야 되는 상황이 있어요
-> 그러므로 데이터 전처리는 되도록이면 RDD 사용하지 않고 서버리스 컴퓨터에서 해주세요.

- 한번에 모든걸 하려지 말고 아래와 같은 형태로 해보시겠어요?
(어떤 함수를 실행해서 새로운 데이터를 만들었으면 별도 저장해서, 다음에 읽을때는 저장된 데이터를 읽고 이어서 진행)

(예시) 다음과 같은 형태
1) df_proc = data_processing(df) <-  data_processing 함수는 예로 들었습니다.
2) df_proc.write.mode("overwrite").saveAsTable("table 명")
3) df_table = spark.read.table("table 명")
4) 다른 함수 수행할 때 df_proc로 연결하지 않고 df_table로 연결하기 
-> df_category = data_category_processing(df_table) 

- 스파크가 lazy evaluation이라서 계속 기존 객체를 연결해서 사용하면 앞에서부터 처음까지 모든걸 재실행 합니다. 그러므로 비효율적이며 메모리가 크게 사용됩니다.
- 설하님 데이터 전처리할 때 급하더라도 객체명은 헷갈리지 않고 구별해서 쓰시는게 좋을 듯 해요. (df1, df2.. df3 이런식으로 하진 마시고)
-뒤에 있는 one_hot_encode_categories 함수에서 카테고리는 rdd.collect()로 뽑지 말고 직접 쿼리로 뽑든 알고 있으니깐 직접 넣으시면 될듯 해요 (rdd 를 굳이 안써도 되는데 rdd를 사용하고 있음)
# 고유한 카테고리 값을 추출 <- 여기에는 카테고리 명을 직접 위에서 출력한 데이터를 넣으면 RDD 를 사용할 필요가 없습니다. 대신 뒤에서 사용할 데이터 구조만 잘 맞춰주심 될듯 해요.
distinct_categories1 = ["",""]
distinct_categories2 = ["",""]

그래서 종합하자면 아래와 같습니다.
-> 데이터 처리는 분리해서 하고 저장한 다음, 저장한 데이터를 다른 객체가 불러와서 해당 객체로 이어서 분석 진행  (서버리스 컴퓨터가 스파크 자원을 더 많이 활용할 수 있으니 되도록 서버리스에서 하기, 모든 데이터 전처리를 한번에 하려고 하지 않기 <- pandas 랑 다름)

**Comment by Seolhada** [comment]
![image](https://github.com/user-attachments/assets/f34e5516-ad25-4fb2-86fb-f658fa591abe)
@syleeie2310 
1) 멘토님 이해가 잘 안가는 부분이 있어서 그런데요. df에 카운트를 찍어봤을 때와 table로 저장한 후 불러와 카운트를 찍어봤을 때의 카운트 수가 다르다면 왜 그럴까요? 
2) 저장 전에는 0라벨의 수가 1라벨에 비해 1,000여개 정도 많았는데 이는 매우 적은 비율이라 1:1이라 생각하고 진행하려했습니다. 
저장 후에 불러와서 카운트 해보면 0라벨의 수가 1라벨에 비해 약 800개 정도 적어집니다. 큰 문제가 되지 않는 부분이라면 그냥 이대로 진행할까요?

**Comment by syleeie2310** [comment]
@Seolhada https://velog.io/@crescent702/Spark%EC%97%90%EC%84%9C-sample-API-%EC%95%8C%EA%B3%A0-%EC%93%B0%EA%B8%B0 이거 때문에 다르대요!

**Comment by syleeie2310** [comment]
피쳐 엔지니어링 -> gmap_id 1/2의 직전 분기 리뷰수, 유니크한 유저수, 직전 1년 간의 평균 평점
결측치 -9999, -1, 0 (tree)
모델 3개를 train 5백만개 데이터를 prediction 해서 결과 저장하기

**Comment by syleeie2310** [comment]
>def linear_trainStadScaler(traindata, testdata, feature_list, feature_category, link_param, family_param):
    start = dt.datetime.now()

    ### Model Data
    traindata_dt = traindata.na.fill(0)
    testdata_dt = testdata.na.fill(0)

    all_dt = traindata_dt.union(testdata_dt)    
    
    indexers = [
        StringIndexer(inputCol=c, outputCol="{0}_indexed".format(c)).setHandleInvalid("keep")
        for c in feature_category
    ]

    # The encode of indexed vlaues multiple columns
    encoders = [OneHotEncoder(dropLast=False,inputCol=indexer.getOutputCol(),
                outputCol="{0}_encoded".format(indexer.getOutputCol())) 
        for indexer in indexers
    ]
    
    vectorAssembler = VectorAssembler(inputCols=feature_list + [encoder.getOutputCol() for encoder in encoders], outputCol='features')
    pipeline  = Pipeline(stages=indexers + encoders+[vectorAssembler])
 
    all_dt_m = pipeline.fit(all_dt)
    traindata_dt_tm = all_dt_m.transform(traindata_dt).select(['features', 'label'])
    testdata_dt_tm = all_dt_m.transform(testdata_dt).select(['features', 'label'])

    scaler = StandardScaler(inputCol="features", outputCol="scaledFeatures", withStd=True, withMean=False)
    
    traindata_scalerModel = scaler.fit(traindata_dt_tm.select("features"))
    
    traindata_dt_stm = traindata_scalerModel.transform(traindata_dt_tm)
    testdata_dt_stm = traindata_scalerModel.transform(testdata_dt_tm)

    (traindf, vaildf) = traindata_dt_stm.randomSplit([0.8, 0.2], seed=2310)

    ### Model Traininig
    lr = GeneralizedLinearRegression(featuresCol = 'scaledFeatures', labelCol = 'label', family=family_param, link=link_param, regParam=0.3)
    
    lrModel = lr.fit(traindf)
    trainingSummary = lrModel.summary
    train_predictions = lrModel.transform(traindf)
    valid_predictions = lrModel.transform(vaildf)
    test_predictions = lrModel.transform(testdata_dt_stm)

    ### Classification Model Performance    
    evaluator = RegressionEvaluator(labelCol="label", predictionCol="prediction", metricName="rmse")
    print ("(train) Root Mean Squared Error (RMSE) is {}".format(evaluator.evaluate(train_predictions)))
    print ("(vaild) Root Mean Squared Error (RMSE) is {}".format(evaluator.evaluate(valid_predictions)))
    print ("(test) Root Mean Squared Error (RMSE) is {}".format(evaluator.evaluate(test_predictions)))

    print ("Model : Coefficients: " + str(lrModel.coefficients) + "Intercept: " + str(lrModel.intercept))
    #print("Coefficient Standard Errors: " + str(trainingSummary.coefficientStandardErrors))
    print("T Values: " + str(trainingSummary.tValues))
    print("P Values: " + str(trainingSummary.pValues))
    print("Dispersion: " + str(trainingSummary.dispersion))
    print("Null Deviance: " + str(trainingSummary.nullDeviance))
    print("Residual Degree Of Freedom Null: " + str(trainingSummary.residualDegreeOfFreedomNull))
    print("Deviance: " + str(trainingSummary.deviance))
    print("Residual Degree Of Freedom: " + str(trainingSummary.residualDegreeOfFreedom))
    print("AIC: " + str(trainingSummary.aic))
    print("Deviance Residuals: ")

    ### Recommend Model Performance
    train_predictions = lrModel.transform(traindata_dt_stm)
    train_predictions.createOrReplaceTempView("train_predictions")
    test_predictions.createOrReplaceTempView("test_predictions")

    display(
        spark.sql("""
    select 'train' as type, sum(1) cnts, (sum(case when diff_paid_day = 0 then 1 else 0 end) / sum(1)) as ratio
    from(
    select *, round(prediction,0) - label as diff_paid_day
    from train_predictions
    ) as t
    union 
    select 'test' as type, sum(1) cnts, (sum(case when diff_paid_day = 0 then 1 else 0 end) / sum(1)) as ratio
    from(
    select *, round(prediction,0) - label as diff_paid_day
    from test_predictions
    ) as t    
    """))
          
    end = dt.datetime.now() - start
    print (end)  
    return(lrModel, trainingSummary, train_predictions, test_predictions)

**Comment by Seolhada** [comment]
@syleeie2310 
멘토님 랭킹평가 진행 중 헷갈리는 부분이 있어 질문드립니다....!
정답지와 순위비교할 때 정답지에도 co_count 4 이상인 쌍만 남겨두고 비교하는게 맞을까요?
아니면 정답지 전체와 비교하는게 맞을까요?

test 데이터셋은 73,293,810개이고, 그 중 4 이상인 건 590,539개 입니다
그리고 모델 기준으로 1을 예측한 추천 대상들은 gmap_id1을 기준으로 비교할거라 대칭쌍을 만들어 1,014,072개입니다!

**Comment by syleeie2310** [comment]
랭킹 평가에서는 이전에 말했던거 같은데 제외하지 않고 전체를 쓰시면 됩니다. (co-count 4 이상으로 필터링 하지 않고 전체 사용)

**Comment by syleeie2310** [comment]
비교 대상은 아래와 같아요.
- traindata 모델 결과 데이터 -> gmap1, gmap2, prob 확률 계산 하기 (모델 3개이면 각각)
- testdata (평가 데이터)에 있는 co-count (필터링 하지 않는) 값과 랭킹 비교

기존 기수 (43~44페이지) 참고!
https://docs.google.com/presentation/d/1OIhY20PA1lFkjQpAZ-S5G3iB1IG67m1D/edit#slide=id.p61

**Comment by Seolhada** [comment]
@syleeie2310 
test 데이터셋 gmap_id1,2 기준으로 sum했을 때 데이터 개수 64,858,088개 입니다

**Comment by Seolhada** [comment]
@syleeie2310 
멘토님 train 전체의 predicion을 구해야하는데, train 전체는 전처리되어있는게 없어서 모델을 돌릴 수가 없습니다.
카테고리 컬럼을 추가하면 시간이 너무 오래걸려 불가능할 것 같고, 
카테고리 컬럼의 feature importance가 낮았으니 카테고리 컬림을 제거하는게 어떨까 싶습니다.
카테고리 컬럼 제거하고 모델을 다시 돌린 후 진행해도 될까요?

**Comment by syleeie2310** [comment]
@Seolhada 아이템 to 아이템 (텍스트 피쳐 성능 추가했을 때) 랭킹 평가까지 마무리 하기~ (수요일까지)

**Comment by Seolhada** [comment]
랭킹평가 정리 자료입니다
https://quirky-age-880.notion.site/db0aebfeeec644f08969bea1046a3e13?pvs=4
